#!/usr/bin/env python3
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
SNIPPET_PATH = os.path.join(ROOT, 'assets', 'highlevel-snippet.html')

def main():
    if not os.path.exists(SNIPPET_PATH):
        raise SystemExit(f"Snippet not found: {SNIPPET_PATH}")
    with open(SNIPPET_PATH, 'r', encoding='utf-8', errors='ignore') as f:
        snippet = f.read().strip()
    if not snippet:
        raise SystemExit("Snippet file is empty. Paste or generate your HighLevel code into assets/highlevel-snippet.html")

    injected = 0
    for name in os.listdir(ROOT):
        if not name.endswith('.html'):
            continue
        p = os.path.join(ROOT, name)
        with open(p, 'r', encoding='utf-8', errors='ignore') as f:
            html = f.read()

        marker = "<!-- Auto-generated by tools/wire_highlevel.py -->"
        if marker in html:
            # Replace existing auto-generated block up to </body>
            pattern = re.compile(r"<!-- Auto-generated by tools/wire_highlevel.py -->[\s\S]*?</body>", re.I)
            new_html, n = re.subn(pattern, lambda m: snippet + "</body>", html, count=1)
        else:
            # Fresh inject before </body>
            new_html, n = re.subn(r"</body>", lambda m: snippet + "\n</body>", html, count=1, flags=re.IGNORECASE)
        if n:
            with open(p, 'w', encoding='utf-8') as f:
                f.write(new_html)
            injected += 1

    print(f"Injected HighLevel snippet into {injected} pages")

if __name__ == '__main__':
    main()
