#!/usr/bin/env python3
import json
import os
import re
import json as _json

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
CFG_PATH = os.path.join(ROOT, 'data', 'highlevel.json')
SNIPPET_PATH = os.path.join(ROOT, 'assets', 'highlevel-snippet.html')
SITE_CFG = os.path.join(ROOT, 'data', 'site.json')
TRACKING_CFG = os.path.join(ROOT, 'data', 'tracking.json')


def read_cfg():
    with open(CFG_PATH, 'r', encoding='utf-8') as f:
        return json.load(f)


def build_snippet(cfg: dict) -> str:
    parts = ["<!-- Auto-generated by tools/wire_highlevel.py -->"]
    # Load site info
    site_url = "https://proppy.com.au"
    org_name = "Proppy"
    logo_path = "/proppy-logo.png"
    telephone = ""
    same_as = []
    try:
        with open(SITE_CFG, 'r', encoding='utf-8') as sf:
            s = json.load(sf)
            site_url = (s.get('site_url') or site_url).rstrip('/')
            org_name = (s.get('org_name') or org_name)
            logo_path = (s.get('logo_path') or logo_path)
            telephone = (s.get('telephone') or '')
            same_as = s.get('same_as') or []
    except Exception:
        pass

    chat_raw = (cfg.get('chat_widget_raw') or '').strip()
    if chat_raw:
        parts.append(chat_raw)
    else:
        chat_id = (cfg.get('chat_widget_id') or '').strip()
        chat_src = (cfg.get('chat_widget_src') or '').strip() or 'https://cdn.leadconnectorhq.com/js/chat-widget-v3.1.min.js'
        if chat_id:
            parts.append(
                f'<script src="{chat_src}" data-id="{chat_id}" async></script>'
            )

    tracking_raw = (cfg.get('tracking_raw') or '').strip()
    if tracking_raw:
        parts.append(tracking_raw)
    else:
        tracking_org = (cfg.get('tracking_org') or '').strip()
        tracking_src = (cfg.get('tracking_src') or '').strip() or 'https://cdn.leadconnectorhq.com/js/site-tracking.min.js'
        if tracking_org:
            parts.append(
                f'<script src="{tracking_src}" data-org="{tracking_org}" async></script>'
            )

    # Optional Meta Pixel raw snippet
    meta_pixel_raw = (cfg.get('meta_pixel_raw') or '').strip()
    if meta_pixel_raw:
        parts.append(meta_pixel_raw)

    # Organization JSON-LD
    # Build Organization/LocalBusiness JSON-LD
    org_type = "Organization"
    address_obj = None
    opening_cfg = None
    contact_points = None
    try:
        with open(SITE_CFG, 'r', encoding='utf-8') as sf:
            s2 = json.load(sf)
            address_obj = s2.get('address')
            if address_obj:
                org_type = "LocalBusiness"
            opening_cfg = s2.get('opening_hours')
            contact_points = s2.get('contact_points')
    except Exception:
        pass

    org = {
        "@context": "https://schema.org",
        "@type": org_type,
        "name": org_name,
        "url": site_url,
        "logo": site_url + logo_path,
    }
    if telephone:
        org["telephone"] = telephone
    if same_as:
        org["sameAs"] = same_as
    if address_obj and isinstance(address_obj, dict):
        org["address"] = {
            "@type": "PostalAddress",
            "streetAddress": address_obj.get("streetAddress", ""),
            "addressLocality": address_obj.get("addressLocality", ""),
            "addressRegion": address_obj.get("addressRegion", ""),
            "postalCode": address_obj.get("postalCode", ""),
            "addressCountry": address_obj.get("addressCountry", "AU")
        }
    # Opening hours (override defaults if provided)
    ohs = []
    if isinstance(opening_cfg, list):
        for block in opening_cfg:
            days = block.get('days') or []
            opens = block.get('opens') or '09:00'
            closes = block.get('closes') or '17:00'
            for d in days:
                ohs.append({"@type": "OpeningHoursSpecification", "dayOfWeek": d, "opens": opens, "closes": closes})
    if not ohs:
        # Fallback Mon–Fri 09:00-17:00
        for d in ["Monday","Tuesday","Wednesday","Thursday","Friday"]:
            ohs.append({"@type": "OpeningHoursSpecification", "dayOfWeek": d, "opens": "09:00", "closes": "17:00"})
    org["openingHoursSpecification"] = ohs

    # Contact points if provided
    if isinstance(contact_points, list) and contact_points:
        cps = []
        for cp in contact_points:
            t = (cp.get('telephone') or '').strip()
            if not t:
                continue
            cps.append({"@type": "ContactPoint", "contactType": cp.get('contactType') or "customer support", "telephone": t})
        if cps:
            org["contactPoint"] = cps
    parts.append('<script type="application/ld+json">' + _json.dumps(org, ensure_ascii=False) + '</script>')

    # GA4 (if configured)
    try:
        with open(TRACKING_CFG, 'r', encoding='utf-8') as tf:
            t = json.load(tf)
            ga4 = (t.get('ga4_measurement_id') or '').strip()
    except Exception:
        ga4 = ''
    if ga4:
        parts.append(f"""
<!-- GA4 -->
<script async src="https://www.googletagmanager.com/gtag/js?id={ga4}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){{dataLayer.push(arguments);}}
  gtag('js', new Date());
  gtag('config', '{ga4}');
</script>
""")

    # External links open in new window (mirror Rank Math setting)
    parts.append("""
<script>(function(){
  document.addEventListener('DOMContentLoaded', function(){
    try{
      var host = location.hostname;
      document.querySelectorAll('a[href^="http"]').forEach(function(a){
        try{
          var u = new URL(a.href);
          if (u.hostname && u.hostname !== host){
            a.setAttribute('target','_blank');
            var rel = (a.getAttribute('rel')||'').split(/\s+/).filter(Boolean);
            if (rel.indexOf('noopener')===-1) rel.push('noopener');
            a.setAttribute('rel', rel.join(' '));
          }
        }catch(e){}
      });
    }catch(e){}
  });
})();</script>
""")

    # GitHub Pages path fix (rewrite absolute /assets and /page links when served from repo pages)
    parts.append('<script src="assets/gh-pages-path.js"></script>')

    if cfg.get('utm_passthrough'):
        parts.append("""
<script>(function(){
  try{
    var qs = location.search ? new URLSearchParams(location.search) : null;
    if (qs) {
      document.addEventListener('DOMContentLoaded', function(){
        document.querySelectorAll('a[href]').forEach(function(a){
          try{
            var u = new URL(a.href, location.href);
            var host = u.hostname || '';
            if (/leadconnectorhq|gohighlevel/.test(host)){
              qs.forEach(function(v,k){ if(!u.searchParams.has(k)) u.searchParams.set(k,v); });
              a.href = u.toString();
            }
          }catch(e){}
        });
        document.querySelectorAll('iframe[src]').forEach(function(iframe){
          try{
            var u = new URL(iframe.src, location.href);
            var host = u.hostname || '';
            if (/leadconnectorhq|gohighlevel/.test(host)){
              qs.forEach(function(v,k){ if(!u.searchParams.has(k)) u.searchParams.set(k,v); });
              if (iframe.src !== u.toString()) iframe.src = u.toString();
            }
          }catch(e){}
        });
      });
    }
  }catch(e){}
})();</script>
""")

    return "\n".join(parts) + "\n"


def write_snippet(snippet: str):
    os.makedirs(os.path.dirname(SNIPPET_PATH), exist_ok=True)
    with open(SNIPPET_PATH, 'w', encoding='utf-8') as f:
        f.write(snippet)


def replace_contact_form(cfg: dict):
    url = (cfg.get('contact_form_url') or '').strip()
    raw = (cfg.get('contact_form_raw') or '').strip()
    form_script_src = (cfg.get('form_embed_script_src') or cfg.get('calendar_embed_script_src') or '').strip()
    if not url and not raw:
        return False
    p = os.path.join(ROOT, 'contact.html')
    if not os.path.exists(p):
        return False
    with open(p, 'r', encoding='utf-8', errors='ignore') as f:
        html = f.read()
    # Skip if an HL form already present
    if (url and url in html) or re.search(r"/widget/form/", html, re.I):
        return False
    pattern = re.compile(r"<form[^>]*name=\"contact\"[\s\S]*?</form>", re.I)
    if raw:
        replacement = raw
    else:
        block = [
            '<div class="hl-form-embed">',
            f'  <iframe src="{url}" style="width:100%; min-height:700px; border:0" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>'
        ]
        if form_script_src:
            block.append(f'  <script src="{form_script_src}" type="text/javascript"></script>')
        block.append('</div>')
        replacement = "\n".join(block)
    new_html, n = pattern.subn(replacement, html, count=1)
    if n:
        with open(p, 'w', encoding='utf-8') as f:
            f.write(new_html)
        return True
    return False


def embed_calendar(cfg: dict):
    url = (cfg.get('calendar_url') or '').strip()
    script_src = (cfg.get('calendar_embed_script_src') or '').strip()
    if not url:
        return False
    p = os.path.join(ROOT, 'book.html')
    if not os.path.exists(p):
        return False
    with open(p, 'r', encoding='utf-8', errors='ignore') as f:
        html = f.read()

    # Remove any existing Calendly blocks and related scripts/noscript
    cleaned = False
    patterns = [
        r"<div[^>]*class=\"[^\"]*calendly-inline-widget[\s\S]*?</div>",
        r"<script[^>]*src=\"https://assets\.calendly\.com/assets/external/widget\.js\"[^>]*></script>",
        r"<noscript>[\s\S]*?</noscript>"
    ]
    new_html = html
    for pat in patterns:
        new_html, n1 = re.subn(pat, '', new_html, flags=re.I)
        if n1:
            cleaned = True
    if cleaned:
        html = new_html
        with open(p, 'w', encoding='utf-8') as f:
            f.write(html)

    # Skip only if a HL booking widget already exists
    if url in html or re.search(r"https?://[^\s\"']+/widget/booking/", html, re.I):
        return cleaned

    # If a Calendly block exists, replace it
    cal_block = re.search(r"<div[^>]*class=\"[^\"]*calendly-inline-widget[\s\S]*?</noscript>", html, re.I)
    if cal_block:
        section = [
            '\n<section class="mt-6">',
            f'  <iframe src="{url}" style="width:100%; height:900px; border:0; overflow:hidden;" scrolling="no" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>'
        ]
        if script_src:
            section.append(f'  <script src="{script_src}" type="text/javascript"></script>')
        section.append('</section>')
        iframe_html = "\n".join(section)
        new_html, n = re.subn(r"<div[^>]*class=\"[^\"]*calendly-inline-widget[\s\S]*?(?:</noscript>)?", iframe_html, html, count=1, flags=re.I)
        if n:
            with open(p, 'w', encoding='utf-8') as f:
                f.write(new_html)
            return True
    def repl(m):
        opening = m.group(0)
        iframe = [
            '\n<section class="mt-6">',
            f'  <iframe src="{url}" style="width:100%; height:900px; border:0; overflow:hidden;" scrolling="no" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>'
        ]
        if script_src:
            iframe.append(f'  <script src="{script_src}" type="text/javascript"></script>')
        iframe.append('</section>\n')
        iframe_html = "\n".join(iframe)
        return opening + iframe_html

    new_html, n = re.subn(r"<main\b[^>]*>", repl, html, count=1, flags=re.I)
    if n:
        with open(p, 'w', encoding='utf-8') as f:
            f.write(new_html)
        return True
    return False


def main():
    if not os.path.exists(CFG_PATH):
        raise SystemExit(f"Missing config file: {CFG_PATH}")
    cfg = read_cfg()
    snippet = build_snippet(cfg)
    write_snippet(snippet)

    changed_contact = replace_contact_form(cfg)
    changed_book = embed_calendar(cfg)

    print("Wired HighLevel:")
    print(f"- Global snippet: {SNIPPET_PATH}")
    print(f"- Contact form updated: {'yes' if changed_contact else 'no change'}")
    print(f"- Book page calendar: {'yes' if changed_book else 'no change'}")
    print("Now run: python3 tools/inject_highlevel_snippet.py")


if __name__ == '__main__':
    main()
